superbuild_add_project(opencv
  DEPENDS eigen
  
  CMAKE_ARGS
  -DCMAKE_CXX_STANDARD=11
  -DCMAKE_CXX_STANDARD_REQUIRED=true
  -DEIGEN_INCLUDE_PATH=<INSTALL_DIR>/include/eigen3
  -DCMAKE_INSTALL_PREFIX=<INSTALL_DIR>/opencv
  -DWITH_FFMPEG=ON
  -DWITH_TBB=ON
  -DWITH_GTK=ON
  -DWITH_V4L=ON
  -DWITH_OPENGL=ON
  -DWITH_CUBLAS=ON
  -DCUDA_NVCC_FLAGS=-D_FORCE_INLINES
  -DWITH_LIBV4L=ON
  -DBUILD_TESTING=false
  -DBUILD_EXAMPLES=false
  -DGFLAGS=false
  )
