

# Sets VV_VERSION_{MAJOR,MINOR,PATCH}
include(${VeloViewSuperBuild_SOURCE_DIR}/../CMake/version.cmake)
set(VV_VERSION "${VV_VERSION_MAJOR}.${VV_VERSION_MINOR}")
set(VV_VERSION_SUFFIX)

# Sets GD_YEAR, GD_MONTH, GD_DAY
include(${VeloViewSuperBuild_SOURCE_DIR}/Projects/getdate.cmake)
GET_DATE()
set(PACKAGE_TIMESTAMP "${GD_DAY}${GD_MONTH}${GD_YEAR}")

# Enable CPack packaging.
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "VeloView")
set(CPACK_PACKAGE_NAME "VeloView")
set(CPACK_PACKAGE_VENDOR "Velodyne Lidar")
set(CPACK_PACKAGE_VERSION_MAJOR ${VV_VERSION_MAJOR})
set(CPACK_PACKAGE_VERSION_MINOR ${VV_VERSION_MINOR})
if (VV_VERSION_SUFFIX)
  set(CPACK_PACKAGE_VERSION_PATCH ${VV_VERSION_PATCH}-${VV_VERSION_SUFFIX})
else()
  set(CPACK_PACKAGE_VERSION_PATCH ${VV_VERSION_PATCH})
endif()

set(CPACK_RESOURCE_FILE_LICENSE "${VeloViewSuperBuild_SOURCE_DIR}/LICENSE")

#set(CPACK_PACKAGE_FILE_NAME
#    "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}-${package_suffix}")

set(CPACK_PACKAGE_FILE_NAME
    "${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH}-${PACKAGE_TIMESTAMP}-${package_suffix}")
